/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tagihan;
import Config.Model;
import Dashboard.Dashboard;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author titam
 */
public class Tagihan extends javax.swing.JFrame {

    /**
     * Creates new form Tagihan
     */
    public int perkwh = 1000;
    public Tagihan() {
        initComponents();
        setLocationRelativeTo(null);
        loadComboPelanggan();
        loadComboDaya();
        loadTable();
        kosong();
    }
    
    private void kosong(){
        tanggal.setText(null);
        id_tagihan.setText(null);
        id_tagihan.setEditable(true);
        penggunaan.setText(null);
        comboDaya.setSelectedItem(this);
        comboPelanggan.setSelectedItem(this);
        simpan_button.setEnabled(true);
        edit_button.setEnabled(false);
        hapus_button.setEnabled(false);
    }
    
    private void loadTable(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("ID Pelanggan");
        model.addColumn("ID Daya");
        model.addColumn("Pengunaan");
        model.addColumn("Tanggal");
        model.addColumn("Total");
        model.addColumn("Status");
        try{
            
            Model TagihanModel = new Model();
            ResultSet res = TagihanModel.getAll("tagihan");
            while(res.next()){
                model.addRow(new Object[]{res.getString(1), res.getString(2),res.getString(3),res.getString(4),res.getString(5), res.getString(6), res.getString(7)});
            }
            jTable1.setModel(model);
        }catch (HeadlessException | SQLException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this,"Kesalahan Combo :  "+  e.getMessage());
        }
    }
    private void loadComboPelanggan(){
        try{
            Model model = new Model();
            ResultSet res = model.getAll("pelanggan");
            while(res.next()){
                comboPelanggan.addItem(res.getString("id"));
            }
        }catch (HeadlessException | SQLException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this,"Kesalahan Combo :  "+  e.getMessage());
        }
    }
    private void loadComboDaya(){
        try{
            Model model = new Model();
            ResultSet res = model.getAll("daya");
            while(res.next()){
                comboDaya.addItem(res.getString("id"));
            }
        }catch (HeadlessException | SQLException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this,"Kesalahan Combo :  "+  e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        simpan_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        hapus_button = new javax.swing.JButton();
        keluar_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        edit_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        kosong_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboPelanggan = new javax.swing.JComboBox<>();
        comboDaya = new javax.swing.JComboBox<>();
        id_tagihan = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        penggunaan = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        simpan_button.setText("Simpan");
        simpan_button.setToolTipText("");
        simpan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_buttonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tanggal");

        hapus_button.setText("Hapus");
        hapus_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus_buttonActionPerformed(evt);
            }
        });

        keluar_button.setText("Keluar");
        keluar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluar_buttonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("ID Daya");

        edit_button.setText("Edit");
        edit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("No Tagihan");

        kosong_button.setText("Kosong");
        kosong_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kosong_buttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("No Pelanggan");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Tagihan");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Penggunaan");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(285, 285, 285))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(simpan_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(keluar_button))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(edit_button)
                                .addGap(18, 18, 18)
                                .addComponent(hapus_button)
                                .addGap(18, 18, 18)
                                .addComponent(kosong_button))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboPelanggan, 0, 147, Short.MAX_VALUE)
                                    .addComponent(id_tagihan))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comboDaya, 0, 147, Short.MAX_VALUE)
                            .addComponent(tanggal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(penggunaan, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(comboDaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(penggunaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(id_tagihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comboPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan_button)
                    .addComponent(hapus_button)
                    .addComponent(keluar_button)
                    .addComponent(edit_button)
                    .addComponent(kosong_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_buttonActionPerformed
        ArrayList<String> data = new ArrayList<String>();
        ArrayList<String> column = new ArrayList<String>();
        Model model = new Model();
        column.add("id");data.add(id_tagihan.getText());
        column.add("id_pelanggan");data.add(comboPelanggan.getSelectedItem().toString());
        column.add("tanggal");data.add(tanggal.getText());
        column.add("id_daya");data.add(comboDaya.getSelectedItem().toString());
        column.add("penggunaan");data.add(penggunaan.getText());
        column.add("status");data.add("Belum");
        column.add("total"); data.add(Integer.toString(Integer.parseInt(penggunaan.getText())*perkwh));
        boolean insert = model.insertSet(data, column, "tagihan");
        if(insert){
            loadTable();
            kosong();
        }
    }//GEN-LAST:event_simpan_buttonActionPerformed

    private void keluar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluar_buttonActionPerformed
        Dashboard dashboard = new Dashboard();
        dashboard.show();
        this.show(false);
    }//GEN-LAST:event_keluar_buttonActionPerformed

    private void edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_buttonActionPerformed
       // edit tagihan
        ArrayList<String> data = new ArrayList<String>();
        ArrayList<String> column = new ArrayList<String>();
        Model model = new Model();
        ResultSet resTagihan = model.getDataById("tagihan", "id", id_tagihan.getText());
        try {
            if(resTagihan.next()){
                if (resTagihan.getString("status").equals("selesai")){
                    JOptionPane.showMessageDialog(this, "Tagihan sudah selesai");
                }else{
                    column.add("id_pelanggan");data.add(comboPelanggan.getSelectedItem().toString());
                    column.add("id_daya");data.add(comboDaya.getSelectedItem().toString());
                    column.add("penggunaan");data.add(penggunaan.getText());
                    column.add("tanggal");data.add(tanggal.getText());
                    column.add("total");data.add(Integer.toString( Integer.parseInt(penggunaan.getText())*perkwh));
                    boolean update =  model.update(data, column, "tagihan", "id", id_tagihan.getText());
                    if(update){
                        loadTable();
                        kosong();
                    }
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error : "+e.getMessage());
        }


    }//GEN-LAST:event_edit_buttonActionPerformed

    private void kosong_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kosong_buttonActionPerformed
        kosong();
    }//GEN-LAST:event_kosong_buttonActionPerformed

    private void hapus_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_buttonActionPerformed
        // hapus tagihan
        Model model = new Model();
        boolean delete = model.delete("tagihan", "id", id_tagihan.getText());
        if(delete){
            loadTable();
            kosong();
        }
    }//GEN-LAST:event_hapus_buttonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        id_tagihan.setText(jTable1.getValueAt(row, 0).toString());
        id_tagihan.setEnabled(false);
        comboPelanggan.setSelectedItem(jTable1.getValueAt(row, 1).toString());
        comboDaya.setSelectedItem(jTable1.getValueAt(row, 2).toString());
        penggunaan.setText(jTable1.getValueAt(row, 3).toString());
        tanggal.setText(jTable1.getValueAt(row, 4).toString());
        
        edit_button.setEnabled(true);
        hapus_button.setEnabled(true);
        simpan_button.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tagihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tagihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tagihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tagihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try{            
            javax.swing.UIManager.setLookAndFeel(new FlatIntelliJLaf());   
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Tagihan().setVisible(true);
                }
            });
        }catch(UnsupportedLookAndFeelException ex) {
            System.out.println("error theme : " + ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboDaya;
    private javax.swing.JComboBox<String> comboPelanggan;
    private javax.swing.JButton edit_button;
    private javax.swing.JButton hapus_button;
    private javax.swing.JTextField id_tagihan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton keluar_button;
    private javax.swing.JButton kosong_button;
    private javax.swing.JTextField penggunaan;
    private javax.swing.JButton simpan_button;
    private javax.swing.JTextField tanggal;
    // End of variables declaration//GEN-END:variables
}
